openapi: "3.0.0"

info:
  version: "1.0.0"
  title: TODO API

servers:
  - url: /api/v1

paths:

  /todo/:

    get:
      summary: List of my TODO items
      operationId: todo.list
      responses:
        '200':
          description: A list of my TODO items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Item"

    post:
      summary: Create a TODO item
      operationId: todo.create
      requestBody:
        required: true
        description: Data for creating a new TODO item
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'

      responses:
        '400':
          $ref: '#/components/responses/BadRequest'

        '200':
          description: The item that was created
          content:
            application/json:
              schema:
                type: string

components:

  schemas:

    Item:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 40

  responses:

    BadRequest:
      description: OpenAPI request/response validation failed
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
