openapi: "3.0.0"

info:
  version: "1.0.0"
  title: Drinks API

servers:
  - url: /api/v1

paths:

  /drinks/:
    get:
      summary: What did I have to drink tonight?
      operationId: drink.list
      responses:
        '200':
          description: A list of drinks I had tonight
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Drink"

    post:
      summary: Record a drink
      operationId: drink.record
      requestBody:
        required: true
        description: Specification for recording a drink
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Drink'
      responses:
        '400':
          $ref: '#/components/responses/BadRequest'

        '200':
          description: A drink that was recorded
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Drink"

components:

  schemas:

    Drink:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          maxLength: 10

  responses:

    BadRequest:
      description: OpenAPI request/response validation failed
      content:
        application/json:
          schema:
            type: array
            items:
              type: string
